name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Gradle 6.8
        run: |
          wget https://services.gradle.org/distributions/gradle-6.8-bin.zip
          unzip -qq gradle-6.8-bin.zip
          export GRADLE_HOME=$PWD/gradle-6.8
          export PATH=$GRADLE_HOME/bin:$PATH
      - name: Build with Gradle
        run: gradle build

        # ankushk143/notepad_1
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ankushk143/notepad_1
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          token: ${{secrets.DOCKERHUB_TOKEN}}
